Modify README.md.
Fortran-jp/fortran-jp.org pull request #23
Opened 2022-03-11 15:20 UTC by osada-yum

## fortran-jpとは?
## 階層
## コミュニティ
## websiteの内容の変更・追加をしたい場合
を追加しました.

## fortran-jpとは? は想像で書いたので, この考えが合致しているかは分かりませんでした.

2022-03-12 01:29 UTC, sakamoti commented on README.md
> +そのような場合でも, 人やコミュニティに質問しやすい環境ならば, 言語の悪口を言いたくなるような状況が減るかもしれません.
確かに、Fortranの情報が少なく「孤立」感を抱いていたり、Fortranに対する「悪口」を言われるといった状況があるかもしれませんが、レポジトリのトップに出てくる文面としては、もう少しポジティブな印象が欲しいと感じました。
index.mdに記載のあるように、「Fortran-langコミュニティ活動に大いに賛同するとともに，Fortranの若返りの動きを日本でも推し進めたい」というのが、このレポジトリの目的だと私は受けとっています。

@osada-yum  さんの文案を元に下記を考えましたが、いかがでしょうか。

```
Fortranユーザ同士の情報共有を目的としています．

Fortranは古くから存在するプログラミング言語であり，レガシーコードへの対処に迫られる場面も多いと思われます．
そのような場合にネット上でのFortran情報を検索すると，古いもの(もしくは非推奨なもの)と新しいものの区別が分かりづらく，2022年時点の日本語書籍においても古い情報(おおよそf90以前)が多い状態です．

本コミュニティでは、Fortran-langコミュニティ活動に大いに賛同するとともに，開かれた質問しやすい環境を構築することで，日本におけるFortranの若返りの動きを推し進めたいと考えています．
```

2022-03-12 02:13 UTC, osada-yum commented on README.md
> +そのような場合でも, 人やコミュニティに質問しやすい環境ならば, 言語の悪口を言いたくなるような状況が減るかもしれません.
孤立 ↔ コミュニティ
みたいな対比として, 「孤立」は必要かなと思っています.

「悪口」はたしかに, 要らない気がします.

レガシーコードへの対処と(なにか初学者ユーザに関する問題)を列挙して語りたいと思いました. (良いフレーズが思い浮かびません...情報が少なく, f77を使うことなど?)

後は同意です. 

「Fortran-langコミュニティ」へのリンクや「質問しやすい環境」(GithubのDiscussionsの項目)の説明も加えるべきかもしれません.

2022-03-12 07:08 UTC, sakamoti commented on README.md
> +そのような場合でも, 人やコミュニティに質問しやすい環境ならば, 言語の悪口を言いたくなるような状況が減るかもしれません.
対比であれば、index.htmlの文言がよく纏まっているので、これを拝借いたしました。
「問題の列挙」は、分量が多くなりそうなので他の項目(README以外)へ譲る方が書きやすいのではないでしょうか。
下記にざっくり書いてみましたが、私の認識違いもあると思いますので、他の方のご意見も頂けますと幸いです。

また、Discussionsの「投稿のルール  #15」などが纏まってきたら、適宜修正・加筆していく前提が良いと思っています。

```
本コミュニティは、2019年頃に海外で開始されたFortran-langコミュニティの活動に大いに賛同し，日本におけるFortranの若返りの動きを推し進めたいという方針のもと活動しています．

Fortranは古くから存在するプログラミング言語であり，レガシーコードへの対処に迫られる場面も多いと思われます．
そのような場合にネット上でのFortran情報を検索すると，古いもの(もしくは非推奨なもの)と新しいものの区別が分かりづらく，2022年時点の日本語書籍においても古い情報(おおよそf90以前)が多い状態です．

Fortranには広く横断的なコミュニティがないため，ユーザが孤立し，問題の解決法にたどり着けず，車輪の再実装が行われています．そして，それに疲弊したユーザがFortranから離れてしまうという分析が示されています．
この状況を改善するために，Fortran-langコミュニティが立ち上げられ，標準ライブラリ，パッケージマネージャ，モダンなコンパイラの開発が開始されました．

日本語による議論や情報提供の場として，github上のDiscussionsや，コーディングスタイルの解説等を準備しましたので，皆様の参加をお待ちしております。

```

2022-03-15 11:01 UTC, degawa commented on README.md
> +そのような場合でも, 人やコミュニティに質問しやすい環境ならば, 言語の悪口を言いたくなるような状況が減るかもしれません.
内容についてはレビューしていますが，Webページのレイアウトでの確認ができないので，その方法を探しています．
もう少しお待ちください:bow:

2022-03-20 05:23 UTC, degawa requested changes
変更の提案ありがとうございます．
まずはご提案の文言を反映した上で，徐々にポジティブな方向に修正をしていくようにしたいと思います．
また，インターネット上の情報が古いために，新しい規格の導入やリファクタリングが妨げられること（明示的に妨害しているのではなく，あることを知らない）は事実だと思いますので，今後言及はしていきたいと考えています．

1点，悪口を不平不満と言い換えましたので，修正をお願いします．

2022-03-20 05:23 UTC, degawa commented on README.md
> +そのような場合でも, 人やコミュニティに質問しやすい環境ならば, 言語の悪口を言いたくなるような状況が減るかもしれません.
```suggestion
そのような場合でも, 人やコミュニティに質問しやすい環境ならば, 言語に対する不平不満が減るかもしれません.
```

2022-03-21 00:16 UTC, degawa approved these changes
確認しました．加筆・修正対応ありがとうございます．
マージします:thumbsup:

2022-03-21 00:16 UTC, merged